<script>
  import geojsonUrl1 from "../data/oa_scores_1.geojson?url";
  import geojsonUrl2 from "../data/oa_scores_2.geojson?url";
  import geojsonUrl3 from "../data/oa_scores_3.geojson?url";
  import geojsonUrl4 from "../data/oa_scores_4.geojson?url";
  import geojsonUrl5 from "../data/oa_scores_5.geojson?url";
  import geojsonUrl6 from "../data/oa_scores_6.geojson?url";

  import { onMount, getContext } from "svelte";

  const { getMap } = getContext("map");
  const map = getMap();

  const source = "baselineOA";
  const layer = "baseline_layerOA";

  export let hoveredAreaScores;
  export let displayAreaLevel;
  export let responseJson;

  let scoreLayer = "Hide";

  onMount(async () => {
    let pair = await loadBasecores();
    let geojsonData = pair[0];
    map.addSource(source, {
      type: "geojson",
      data: geojsonData,
    });
    setLayer();

    map.on("mousemove", layer, function (e) {
      if (e.features.length > 0) {
        hoveredAreaScores = e.features[0].properties;
      }
    });
    map.on("mouseleave", layer, function () {
      hoveredAreaScores = null;
    });
  });

  function setLayer() {
    if (map.getLayer(layer)) {
      map.removeLayer(layer);
    }
    if (scoreLayer != "Hide") {
      map.addLayer({
        id: layer,
        source: source,
        type: "fill",
        paint: {
          "fill-color": [
            "interpolate",
            ["linear"],
            ["get", scoreLayer],
            10,
            "#67001f",
            20,
            "#b2182b",
            30,
            "#d6604d",
            40,
            "#f4a582",
            50,
            "#fddbc7",
            60,
            "#d1e5f0",
            70,
            "#92c5de",
            80,
            "#4393c3",
            90,
            "#2166ac",
            100,
            "#053061",
          ],
          "fill-outline-color": "rgba(0, 0, 0, 0.2)",
          "fill-opacity": 0.7,
        },
      });
    }
  }

  function scoreTypes() {
    let purposes = [
      "Business",
      "Education",
      "Shopping",
      "Residential",
      "Entertainment",
    ];
    let modes = ["Driving", "Walking", "Cycling", "PT"];
    let all = ["Hide", "Overall"];

    for (let mode of modes) {
      all.push(`Overall ${mode}`);
    }

    for (let purpose of purposes) {
      all.push(`Overall ${purpose}`);
      for (let mode of modes) {
        all.push(`${purpose} by ${mode}`);
      }
    }
    return all;
  }

  // Returns the baseline GeoJSON data and also a dictionary from LSOA ID to
  // geometry (to later display recalculated scores)
  async function loadBasecores() {
    const [resp1, resp2, resp3, resp4, resp5, resp6] = await Promise.all([
      fetch(geojsonUrl1),
      fetch(geojsonUrl2),
      fetch(geojsonUrl3),
      fetch(geojsonUrl4),
      fetch(geojsonUrl5),
      fetch(geojsonUrl6),
    ]);
    const [geojson, geojson2, geojson3, geojson4, geojson5, geojson6] =
      await Promise.all([
        resp1.json(),
        resp2.json(),
        resp3.json(),
        resp4.json(),
        resp5.json(),
        resp6.json(),
      ]);
    // Merge the features of geojson2 into geojson1
    geojson.features = [
      ...geojson.features,
      ...geojson2.features,
      ...geojson3.features,
      ...geojson4.features,
      ...geojson5.features,
      ...geojson6.features,
    ];

    // "Uncompress" the string properties
    // This mapping is generated by shrink_gj.py
    let mapping = {
      "0": "Area",
      "1": "Business by Driving",
      "2": "Education by Driving",
      "3": "Entertainment by Driving",
      "4": "Shopping by Driving",
      "5": "Residential by Driving",
      "6": "Business by Walking",
      "7": "Education by Walking",
      "8": "Entertainment by Walking",
      "9": "Shopping by Walking",
      "10": "Residential by Walking",
      "11": "Business by PT",
      "12": "Education by PT",
      "13": "Entertainment by PT",
      "14": "Shopping by PT",
      "15": "Residential by PT",
      "16": "Business by Cycling",
      "17": "Education by Cycling",
      "18": "Entertainment by Cycling",
      "19": "Shopping by Cycling",
      "20": "Residential by Cycling",
      "21": "Overall PT",
      "22": "Overall Cycling",
      "23": "Overall Driving",
      "24": "Overall Walking",
      "25": "Overall Shopping",
      "26": "Overall Business",
      "27": "Overall Education",
      "28": "Overall Entertainment",
      "29": "Overall Residential",
      "30": "Overall",
    };
    for (let feature of geojson.features) {
      let props = {};
      for (let [k, v] of Object.entries(feature.properties)) {
        props[mapping[k]] = v;
      }
      feature.properties = props;
    }

    // Make a copy of the geometry, keyed by LSOA ID
    let lsoaGeometry = {};
    for (let feature of geojson.features) {
      let id = feature.properties["LSOA11CD"];
      lsoaGeometry[id] = feature.geometry;
    }

    return [geojson, lsoaGeometry];
  }

  function resetScoreLayer() {
    scoreLayer = "Hide";
    setLayer();
  }
</script>

{#if responseJson}
  {resetScoreLayer()}
{/if}

{#if displayAreaLevel == "OA"}
  <div class="govuk-form-group" style="display: flex;">
    <label
      class="govuk-label"
      for="scoreLayer"
      style="margin-right: 10px; margin-top: 8px; font-size: 1rem;"
    >
      OA scores:
    </label>
    <select
      class="govuk-select"
      id="scoreLayer"
      name="scoreLayer"
      bind:value={scoreLayer}
      on:change={setLayer}
    >
      {#each scoreTypes() as x}
        <option value={x}>{x}</option>
      {/each}
    </select>
  </div>
{:else}
  {resetScoreLayer()}
{/if}

<style>
  div {
    z-index: 1;
    position: absolute;
    bottom: 97px;
    right: 65px;
    background: white;
    padding: 5px;
    border-radius: 10px;
    box-shadow: 2px 3px 3px rgba(0, 0, 0, 0.2);
  }

  select {
    font-size: 16px;
    padding: 4px 8px;
  }
</style>
