<script>
  import geojsonUrl from "../data/s38i_oa_2022_all_modes.geojson?url";

  import { onMount, getContext } from "svelte";

  const { getMap } = getContext("map");
  const map = getMap();

  const source = "baselineOA";
  const layer = "baseline_layerOA";

  export let hoveredAreaScores;
  export let displayAreaLevel;
  export let responseJson;

  let scoreLayer = "Hide";

  onMount(async () => {
    let pair = await loadBasecores();
    let geojsonData = pair[0];
    map.addSource(source, {
      type: "geojson",
      data: geojsonData,
    });
    setLayer();

    map.on("mousemove", layer, function (e) {
      if (e.features.length > 0) {
        hoveredAreaScores = e.features[0].properties;
      }
    });
    map.on("mouseleave", layer, function () {
      hoveredAreaScores = null;
    });
  });

  function setLayer() {
    if (map.getLayer(layer)) {
      map.removeLayer(layer);
    }
    if (scoreLayer != "Hide") {
      map.addLayer({
        id: layer,
        source: source,
        type: "fill",
        paint: {
          "fill-color": [
            "interpolate",
            ["linear"],
            ["get", scoreLayer],
            10,
            "#67001f",
            20,
            "#b2182b",
            30,
            "#d6604d",
            40,
            "#f4a582",
            50,
            "#fddbc7",
            60,
            "#d1e5f0",
            70,
            "#92c5de",
            80,
            "#4393c3",
            90,
            "#2166ac",
            100,
            "#053061",
          ],
          "fill-outline-color": "rgba(0, 0, 0, 0.2)",
          "fill-opacity": 0.7,
        },
      });
    }
  }

  function scoreTypes() {
    return ['Hide',
            'oa11cd',
            'Business_car',
            'Education_car',
            'Health_car',
            'Entertainment_car',
            'Shopping_car',
            'Residential_car',
            'Business_walk',
            'Education_walk',
            'Health_walk',
            'Entertainment_walk',
            'Shopping_walk',
            'Residential_walk',
            'Business_pt',
            'Education_pt',
            'Health_pt',
            'Entertainment_pt',
            'Shopping_pt',
            'Residential_pt',
            'Business_cycling',
            'Education_cycling',
            'Health_cycling',
            'Entertainment_cycling',
            'Shopping_cycling',
            'Residential_cycling',
            'Overall_pt',
            'Overall_cycling',
            'Overall_car',
            'Overall_walk',
            'Overall_Business',
            'Overall_Education',
            'Overall_Health',
            'Overall_Entertainment',
            'Overall_Shopping',
            'Overall_Residential',
            'Overall_Overall']
  }

  // Returns the baseline GeoJSON data and also a dictionary from LSOA ID to
  // geometry (to later display recalculated scores)
  async function loadBasecores() {
    const resp = await fetch(geojsonUrl);
    const geojson = await resp.json();

    // "Uncompress" the string properties
    // This mapping is generated by shrink_gj.py
    // let mapping = {
    //   "0": "Area",
    //   "1": "Business by Driving",
    //   "2": "Education by Driving",
    //   "3": "Entertainment by Driving",
    //   "4": "Shopping by Driving",
    //   "5": "Residential by Driving",
    //   "6": "Business by Walking",
    //   "7": "Education by Walking",
    //   "8": "Entertainment by Walking",
    //   "9": "Shopping by Walking",
    //   "10": "Residential by Walking",
    //   "11": "Business by PT",
    //   "12": "Education by PT",
    //   "13": "Entertainment by PT",
    //   "14": "Shopping by PT",
    //   "15": "Residential by PT",
    //   "16": "Business by Cycling",
    //   "17": "Education by Cycling",
    //   "18": "Entertainment by Cycling",
    //   "19": "Shopping by Cycling",
    //   "20": "Residential by Cycling",
    //   "21": "Overall PT",
    //   "22": "Overall Cycling",
    //   "23": "Overall Driving",
    //   "24": "Overall Walking",
    //   "25": "Overall Shopping",
    //   "26": "Overall Business",
    //   "27": "Overall Education",
    //   "28": "Overall Entertainment",
    //   "29": "Overall Residential",
    //   "30": "Overall",
    // };
    // for (let feature of geojson.features) {
    //   let props = {};
    //   for (let [k, v] of Object.entries(feature.properties)) {
    //     props[mapping[k]] = v;
    //   }
    //   feature.properties = props;
    // }

    // Make a copy of the geometry, keyed by LSOA ID
    let lsoaGeometry = {};
    for (let feature of geojson.features) {
      let id = feature.properties["oa11cd"];
      lsoaGeometry[id] = feature.geometry;
    }

    return [geojson, lsoaGeometry];
  }

  function resetScoreLayer() {
    scoreLayer = "Hide";
    setLayer();
  }
</script>

{#if responseJson}
  {resetScoreLayer()}
{/if}

{#if displayAreaLevel == "OA"}
  <div class="govuk-form-group" style="display: flex;">
    <label
      class="govuk-label"
      for="scoreLayer"
      style="margin-right: 10px; margin-top: 8px; font-size: 1rem;"
    >
      OA scores:
    </label>
    <select
      class="govuk-select"
      id="scoreLayer"
      name="scoreLayer"
      bind:value={scoreLayer}
      on:change={setLayer}
    >
      {#each scoreTypes() as x}
        <option value={x}>{x}</option>
      {/each}
    </select>
  </div>
{:else}
  {resetScoreLayer()}
{/if}

<style>
  div {
    z-index: 1;
    position: absolute;
    bottom: 97px;
    right: 65px;
    background: white;
    padding: 5px;
    border-radius: 10px;
    box-shadow: 2px 3px 3px rgba(0, 0, 0, 0.2);
  }

  select {
    font-size: 16px;
    padding: 4px 8px;
  }
</style>
